### ISSUE TITLE
Firebase cleanup

### ISSUE THREAD

**Issue by logesixas96** [logesixas96/Android-QR-System#12]
![Firebase](https://user-images.githubusercontent.com/108042238/181698875-8573cfe4-b915-4f13-9234-cf8b8bad95df.png)

@kshorenicholas  Since we are about to release the app, is it ok for you if I erase the entire database to make a fresh start? It seems the current database is full of unused accounts and data as we did much testing and creating 'fake' accounts for testing purpose. The database would look clean and organized if we wipe them out.

**Comment by kshorenicholas** [comment]
I think that's a good idea too

**Comment by kshorenicholas** [comment]
Closing issue as planned
