### ISSUE TITLE
App packaging

### ISSUE THREAD

**Issue by kshorenicholas** [logesixas96/Android-QR-System#6]
@logesixas96 How do you propose we package the application? create an .apk or deploy to the app store?

**Comment by logesixas96** [comment]
For now, I would suggest to create .apk for the purpose of presenting to our supervisor. What do you think?

**Comment by kshorenicholas** [comment]
Noted. I think that would be a good idea too because having to add the application to the Google/IOS app store is more complicated than it seems

**Comment by kshorenicholas** [comment]
It has come to my notice that Google is pushing the use towards Android App Bundles (AABs) as opposed to Android Packages (APKs). We would need to use AAB if we were to publish the app into the Google Play Store. If the user is sideloading the app, the APK should do just fine. Should we proceed with just the APK for now?

**Comment by logesixas96** [comment]
Yes. Since we are not geared up to push our app to the Google Play Store, I guess it is fine to build APKs for now and it is quite straightforward to be distributed and for user testing on physical device.

**Comment by kshorenicholas** [comment]
@logesixas96 Are there any other major changes to make? If there are none, I'll upload the beta apk to Github by today.

**Comment by logesixas96** [comment]
> @logesixas96 Are there any other major changes to make? If there are none, I'll upload the beta apk to Github by today.

None from my side. You can proceed @kshorenicholas

**Comment by kshorenicholas** [comment]
Closing issue as completed
